version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=blog
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: mysql
