version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "127.0.0.1:3306:3306"
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql

volumes:
  mysql:
    name: mysql

networks:
  mysql:
    name: mysql
    driver: bridge
