version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: mysql
